version: '2'
services:
    cosmo-app:
        image: cosmo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cosmo-postgresql:5432/cosmo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cosmo-postgresql:
        extends:
            file: postgresql.yml
            service: cosmo-postgresql
